name: build-docker-310
on:
  push:
    tags:
      - "*"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push alpine 3.10
        id: docker_build_alpine_310
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-alpine
          push: true
          tags: andrewthetechie/complexity-docker:3.10-rc-alpine-${{ steps.get_version.outputs.version }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: |
            complexity_version=${{ steps.get_version.outputs.version }}
            py_ver=3.10-rc
      - name: Build and push slim 3.10
        id: docker_build_slim_310
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-alpine
          push: true
          tags: andrewthetechie/complexity-docker:3.10-rc-slim-${{ steps.get_version.outputs.version }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: |
            complexity_version=${{ steps.get_version.outputs.version }}
            py_ver=3.10-rc
      - name: Image digest alpine 3.10
        run: echo ${{ steps.docker_build_alpine_310.outputs.digest }}
      - name: Image digest slim 3.10
        run: echo ${{ steps.docker_build_slim_310.outputs.digest }}
